---
- name: Stop node and openvswitch services
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
  - openvswitch
  - "{{ openshift_service_type }}-node"
  failed_when: false

- name: Ensure static containerized services stopped before Docker restart
  command: /usr/local/bin/master-restart "{{ item }}"
  with_items:
  - api
  - controllers
  - etcd
  failed_when: false

- service:
    name: docker
    state: stopped
  register: l_openshift_node_upgrade_docker_stop_result
  until: not (l_openshift_node_upgrade_docker_stop_result is failed)
  retries: 3
  delay: 30
  when:
  - l_docker_upgrade is defined
  - l_docker_upgrade | bool
