---
openshift_service_catalog_remove: false
openshift_service_catalog_async_bindings_enabled: true

openshift_use_openshift_sdn: True
# os_sdn_network_plugin_name: "{% if openshift_use_openshift_sdn %}redhat/openshift-ovs-subnet{% else %}{% endif %}"
os_sdn_network_plugin_name: "redhat/openshift-ovs-subnet"

openshift_service_catalog_image: "{{ l_os_registry_url | regex_replace('${component}' | regex_escape, 'service-catalog') }}"
