---
# This script is a special case because we need to pause between nodes while
# labeling to avoid overloading the scheduler.
# Also, looping over this task file (label_and_wait) causes memory to balloon
# in some instances due to dynamic include bug in ansible, so we can't add the
# wait in ansible directly.
- name: Create temporary fluentd labeling script
  template:
    src: fluentd_label.sh.j2
    dest: /tmp/fluentd_label.temp.sh
    mode: "0744"

- name: Execute the fluentd temporary labeling script
  command: "/tmp/fluentd_label.temp.sh {{ fluentd_host }}"
  with_items: "{{ openshift_logging_fluentd_hosts }}"
  loop_control:
    loop_var: fluentd_host

- name: Remove temporary fluentd labeling script
  file:
    path: /tmp/fluentd_label.temp.sh
    state: absent
