---
# add localhost to OSEv3 so we can access OSEv3 inventory variables
- name: Add localhost to OSEv3
  add_host:
    hostname: 'localhost'
    groupname: 'OSEv3'

- name: Check number of master nodes is greater than 0
  assert:
    that: openshift_openstack_num_masters > 0
    msg: "openshift_use_all_in_one_cluster_deployment: openshift_openstack_num_masters must be greater than 0"

- name: Check number of infra nodes is equal to 0
  assert:
    that: openshift_openstack_num_infra == 0
    msg: "openshift_use_all_in_one_cluster_deployment: openshift_openstack_num_infra must be 0"

- name: Check number of app nodes is equal to 0
  assert:
    that: openshift_openstack_num_nodes == 0
    msg: "openshift_use_all_in_one_cluster_deployment: openshift_openstack_num_nodes must be 0"

- name: Check openshift_openstack_master_group_name is set to node-config-all-in-one
  assert:
    that: openshift_openstack_master_group_name == 'node-config-all-in-one'
    msg: "openshift_use_all_in_one_cluster_deployment: openshift_openstack_num_nodes must be set to node-config-all-in-one"

- name: Check openshift_node_groups contains node-config-all-in-one entry
  assert:
    that: openshift_node_groups | selectattr('name', 'equalto', 'node-config-all-in-one') | list | count > 0
    msg: "openshift_use_all_in_one_cluster_deployment: openshift_node_groups must contain a node-config-all-in-one entry"

- name: Clear inventory
  meta: refresh_inventory
