---
# add localhost to OSEv3 so we can access OSEv3 inventory variables
- name: Add localhost to OSEv3
  add_host:
    hostname: 'localhost'
    groupname: 'OSEv3'

- name: Check openshift_cloudprovider_kind value
  assert:
    that: openshift_cloudprovider_kind == 'openstack'
    msg: "openshift_use_cloud_provider: openshift_cloudprovider_kind must be set to openstack"
  when: openshift_cloudprovider_openstack_conf_file is not defined

- name: Check openshift_cloudprovider_openstack_auth_url is defined
  assert:
    that: openshift_cloudprovider_openstack_auth_url is defined
    msg: "openshift_use_cloud_provider: openshift_cloudprovider_openstack_auth_url must be defined"
  when: openshift_cloudprovider_openstack_conf_file is not defined

- name: Check openshift_cloudprovider_openstack_username is defined
  assert:
    that: openshift_cloudprovider_openstack_username is defined
    msg: "openshift_use_cloud_provider: openshift_cloudprovider_openstack_username must be defined"
  when: openshift_cloudprovider_openstack_conf_file is not defined

- name: Check openshift_cloudprovider_openstack_password is defined
  assert:
    that: openshift_cloudprovider_openstack_password is defined
    msg: "openshift_use_cloud_provider: openshift_cloudprovider_openstack_password must be defined"
  when: openshift_cloudprovider_openstack_conf_file is not defined

- name: Check that a openshift_cloudprovider_openstack tenant parameter is defined
  assert:
    that: openshift_cloudprovider_openstack_tenant_id is defined or openshift_cloudprovider_openstack_tenant_name is defined
    msg: "openshift_use_cloud_provider: either openshift_cloudprovider_openstack_tenant_id or openshift_cloudprovider_openstack_tenant_name must be defined"
  when: openshift_cloudprovider_openstack_conf_file is not defined

- name: Clear inventory
  meta: refresh_inventory
