---
id: 2649548
guid: "1021580d-3080-410b-bd3e-8821d8089eaf"
name: "Ansible"
type: "COMPONENT_COMPLETION"
change_description: null
fulfillment_rule: null
add_owner_as_admin: false
auto_deploy: false
users: []
organizations: []
target_type: null
info_messages: []
prompt_message: null
system_version: "trunk (1006050065)"
steps:
- name: "Conditional steps with inline playbook yaml"
  type: "ANSIBLE_RUN_PLAYBOOK"
  condition: "\"#{target.settings.customAttribute['Ansible Playbooks']}\" -contains\
    \ \"apache\""
  data:
    timeout: "300"
    playbook_url: ""
    extra_vars: ""
    playbook_yaml: "-\n  become: true\n  hosts: all\n  tasks:\n    -\n      action:\
      \ ec2_facts\n      name: \"gather ec2 facts\"\n    -\n      name: \"install\
      \ apache on redhat or centos instances\"\n      when: \"ansible_os_family ==\
      \ \\\"RedHat\\\"\"\n      yum: \"name=httpd state=present\"\n    -\n      name:\
      \ \"install apache on debian or ubuntu instances\"\n      when: \"ansible_os_family\
      \ == \\\"Debian\\\"\"\n      apt: \"name=apache2 state=present\"\n    -\n  \
      \    name: \"enable apache on startup and start service for redhat or centos\"\
      \n      when: \"ansible_os_family == \\\"RedHat\\\"\"\n      service: \"name=httpd\
      \ enabled=yes state=started\"\n    -\n      name: \"enable apache on startup\
      \ and start service for debian or ubuntu\"\n      when: \"ansible_os_family\
      \ == \\\"Debian\\\"\"\n      service: \"name=apache2 enabled=yes state=started\""
    os_credentials: "admin"
- name: "Conditional steps with playbook URLs"
  type: "ANSIBLE_RUN_PLAYBOOK"
  condition: "\"#{target.settings.customAttribute['Ansible Playbooks']}\" -contains\
    \ \"nginx\""
  data:
    timeout: "300"
    playbook_url: "http://server.example.com/playbooks/nginx"
    extra_vars: ""
    playbook_yaml: ""
    os_credentials: "admin"
