---
- name: Remove openshift-console project
  oc_project:
    name: openshift-console
    state: absent

- name: Remove openshift-console OAuth client
  oc_obj:
    kind: oauthclient
    name: openshift-console
    state: absent
