# This deletes *ALL* Origin and OpenShift Container Platform content installed by
# ansible.  This includes:
#
#    configuration
#    containers
#    example templates and imagestreams
#    images
#    RPMs
---
- hosts: nodes:masters
  become: yes
  tasks:

  - name: Stop docker service
    service:
      name: docker
      state: stopped
      enabled: no
    failed_when: false
    register: l_docker_restart_docker_in_pb_result
    until: not (l_docker_restart_docker_in_pb_result is failed)
    retries: 3
    delay: 30

  - name: Reset docker-storage-setup
    shell: docker-storage-setup --reset
    failed_when: False

  - name: rm -rf docker config files
    shell: "rm {{ item }} -rf"
    failed_when: False
    with_items:
    - /etc/docker*
    - /etc/sysconfig/docker*
    - /etc/systemd/system/docker*
